version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: qc-cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    command: start-single-node --insecure

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    volumes:
      - minio_data:/data
    ports:
      - "10000:9000"
      - "10001:9001"
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  cockroach-data:
  minio_data:

